### ISSUE TITLE
Android type prediction not fun

### ISSUE THREAD

**Issue by mikeal** [mikeal/gatherbugs#42] opened 2012-07-23 21:22 UTC
https://twitter.com/jswartwood/status/227512102586302466

@mikeal plz add search button or throttled key press ajax on location search. Expectations spoiled by apps using geo loc and type prediction

https://twitter.com/jswartwood/status/227513713391968257

@mikeal Galaxy Nexus; Jelly Bean. Submit via in-keyboard search button worked fine but had to _find_ it. Tried "Save" in-app; took me back

**Comment by jswartwood** [comment] 2012-07-24 15:10
This is basically a dupe of #13.

One other suggestion would be prefetch a list of close _locations_ based on phone geo-location as soon as the "Where?" view shows.

**Closed as completed** 2012-11-26 23:48 UTC
